### ISSUE TITLE
Minor suggestions for the usage of drake

### ISSUE THREAD

**Issue by wlandau** [sol-eng/tensorflow-w-r#3]
First of all, I am super excited to see TensorFlow and [`drake`](https://github.com/ropensci/drake) working together in an RStudio Solutions Engineering repo! What an honor!

I had a look at the [notebook](http://colorado.rstudio.com:3939/content/2159/tensorflow-drake.nb.html), and I have a few suggestions.

## The seed

I recommend using the `seed` argument of [`make()`](https://ropensci.github.io/drake/reference/make.html) rather than creating a target to set the seed. [`drake`](https://github.com/ropensci/drake) already [sets a unique deterministic seed for each target](https://github.com/ropensci/drake/blob/78de526fe131b4858fe783bff996eb3231641bb7/R/exec-meta.R#L9) so that the RNG state is not a race condition (HPC details [here](https://ropenscilabs.github.io/drake-manual/hpc.html)). I really need to make time to write a chapter on how [`drake`](https://github.com/ropensci/drake) handles reproducible pseudo-randomness (ref: https://github.com/ropenscilabs/drake-manual/issues/49). 

## Packages

If you load your packages in the usual way before calling [`make()`](https://ropensci.github.io/drake/reference/make.html) (example [here](https://github.com/wlandau/drake-examples/blob/d9417547a05aec416afbbda913eaf2d44a552d5b/gsp/make.R#L4)) then [`drake`](https://github.com/ropensci/drake) will automatically pass them to the `packages` argument and make sure they are available to each target. Packages loaded within an individual target may not reach other targets, especially if those targets are on other parallel workers or not strictly downstream.

## strings_in_dots

Just an FYI: in development [`drake`](https://github.com/ropensci/drake), soon to be released as version 7.0.0 next month, there will be no need for `strings_in_dots = "literals"`.

**Comment by edgararuiz-zz** [comment]
Thank you @wlandau ! I was going to ask if you could provide some feedback for improvements, so this is perfect!  I'll address them.

**Comment by wlandau** [comment]
Thanks, @edgararuiz! I will let you know if I think of more.

**Comment by edgararuiz-zz** [comment]
@wlandau - I made the changes to address your library and seed recommendations. I'm closing the Issue, and will just keep an eye out when the next version of `drake` comes out to remove the `strings_in_dots` argument.  Thanks again!

**Comment by wlandau** [comment]
Sure, @edgararuiz. The updated plan looks good.
